# Copyright 2019 Red Hat QE CCIT
#
# This module is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This software is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this software. If not, see <http://www.gnu.org/licenses/>.
#
"""Flask app module
View the swagger spec generated by restplus at <host_url>/api/v1/swagger.json
http://localhost:8000/api/v1/swagger.json
"""
import logging.config
import os

from flask import Flask, Blueprint
from rp_preproc import settings
from rp_preproc.api.process.endpoints.process_payload import payload_namespace
from rp_preproc.api.restplus import api


app = Flask(__name__)
logging_conf_path = os.path.normpath(os.path.join(os.path.dirname(__file__),
                                                  '../logging.conf'))
logging.config.fileConfig(logging_conf_path)
log = logging.getLogger(__name__)

app.config['SWAGGER_UI_DOC_EXPANSION'] = \
   settings.RESTPLUS_SWAGGER_UI_DOC_EXPANSION
app.config['RESTPLUS_VALIDATE'] = settings.RESTPLUS_VALIDATE
app.config['RESTPLUS_MASK_SWAGGER'] = settings.RESTPLUS_MASK_SWAGGER
app.config['ERROR_404_HELP'] = settings.RESTPLUS_ERROR_404_HELP

blueprint = Blueprint('api', __name__, url_prefix='/api/v1')
api.init_app(blueprint)
api.add_namespace(payload_namespace)
app.register_blueprint(blueprint)


@app.route('/hello')
def hello():
    """Hello, world test route"""
    return 'hello, world'


def configure_app(flask_app):
    """Configure the flask app"""
    flask_app.config['SWAGGER_UI_DOC_EXPANSION'] = \
        settings.RESTPLUS_SWAGGER_UI_DOC_EXPANSION
    flask_app.config['RESTPLUS_VALIDATE'] = settings.RESTPLUS_VALIDATE
    flask_app.config['RESTPLUS_MASK_SWAGGER'] = settings.RESTPLUS_MASK_SWAGGER
    flask_app.config['ERROR_404_HELP'] = settings.RESTPLUS_ERROR_404_HELP


def main():
    """This is main()"""
    log.info('>>>>> Starting development server at '
             'http://{}/api/ <<<<<'.format(app.config['SERVER_NAME']))
    app.run(host='0.0.0.0', port=8080, debug=settings.FLASK_DEBUG)


if __name__ == "__main__":
    main()
